version: '3'
services:
    frontend:
        image: node:18.16.0
        container_name: frontend
        user: "node"
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
        network_mode: "host"
        command: bash -c "npm install ; npm run dev"
