version: "3"
services:
  backend:
    image: tangramor/nginx-php8-fpm
    environment:
        TZ: 'America/Sao_Paulo'
        WEBROOT: '/var/www/html/public'
        PHP_REDIS_SESSION_HOST: 'redis'
        CREATE_LARAVEL_STORAGE: '1'
        COMPOSERMIRROR: 'https://mirrors.cloud.tencent.com/composer/'
        NPMMIRROR: 'https://registry.npmmirror.com'
    ports:
        - '${APP_PORT:-8000}:80'
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    volumes:
        - '.:/var/www/html'
    networks:
      - networkapi
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "sysdata"
      MYSQL_DATABASE: "sysdata"
      MYSQL_USER: "sysdata"
      MYSQL_PASSWORD: "sysdata"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - networkapi
    security_opt:
      - seccomp:unconfined
networks:
  networkapi:
    driver: bridge
